# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dB8K4RLfqiuXMA9CPb1fCFnybut_orU2
"""

Historial = (2350, 5960, 23000, 1000, 8900)
gastostotalesPuppy = sum (Historial)
if gastostotalesPuppy < 30000:
  print (gastostotalesPuppy)
else:
  print("Gastos por encima de lo presupuestado.")